services:
  - type: web
    name: sv94-bot
    runtime: docker
    envVars:
      - key: LINE_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: GR_USERNAME
        sync: false
      - key: GR_PASSWORD
        sync: false
